collections:
  - name: ansible.posix
    version: 1.5.1
    source: https://galaxy.ansible.com
  - name: community.docker
    version: 3.12.1
    source: https://galaxy.ansible.com
    type: galaxy
roles:
  - name: grycap.htcondor
    src: https://github.com/usegalaxy-eu/ansible-htcondor-grycap
    version: 33ea3aafd9c5d33a1063534e0604631696c052f9
  - name: usegalaxy-eu.autofs
    src: https://github.com/usegalaxy-eu/ansible-autofs
    version: 1.4.0
  - src: https://github.com/usegalaxy-eu/ansible-fw-glxeu-generic
    name: usegalaxy_eu.firewall
    version: 2.0.0
  - src: https://github.com/usegalaxy-eu/ansible-restrict-docker-net
    name: usegalaxy_eu.restrict_docker_net
    version: 0.0.3
  - src: https://github.com/gsaudade99/ansible-cvmfs
    name: galaxyproject.cvmfs
    version: 45c06b395333a468a1ccfd6e05b88d2a37d23e4c
