collections:
  - name: ansible.posix
    version: 1.5.1
    source: https://galaxy.ansible.com
  - name: community.docker
    version: 3.12.1
    source: https://galaxy.ansible.com
    type: galaxy
roles:
  - name: grycap.htcondor
    src: https://github.com/usegalaxy-eu/ansible-htcondor-grycap
    version: d9a4aab0052dfb31d48c986d39a7f5e3692abba4
  - name: usegalaxy-eu.autofs
    src: https://github.com/usegalaxy-eu/ansible-autofs
    version: 1.4.0
  - src: https://github.com/usegalaxy-eu/ansible-fw-glxeu-generic
    name: usegalaxy_eu.firewall
    version: 2.0.0
  - src: https://github.com/usegalaxy-eu/ansible-restrict-docker-net
    name: usegalaxy_eu.restrict_docker_net
    version: 0.0.3
  - src: galaxyproject.cvmfs
    version: 0.5.0
