- name: VGCN Configuration Playbook
  hosts: all
  become: true
  vars_files:
    - mounts/dest/all.yml
    - mounts/mountpoints.yml
  vars:
    internal: true
  handlers:
    - name: Reload Telegraf
      ansible.builtin.service:
        name: telegraf
        state: reloaded
    - name: Reload HTCondor
      ansible.builtin.service:
        name: condor
        state: reloaded
  pre_tasks:
    - name: Ensure the HTCondor configuration directory exists.
      become: true
      ansible.builtin.file:
        path: /etc/condor
        state: directory
        owner: root
        group: root
        mode: "0755"
  post_tasks:
    - name: Template HTCondor local configuration.
      ansible.builtin.template:
        src: condor_config.local.j2
        dest: /etc/condor/condor_config.local
        owner: root
        group: root
        mode: "0644"
      notify: Reload HTCondor
    - name: Template HTCondor host specific configuration.
      ansible.builtin.template:
        src: 99-cloud-init.conf.j2
        dest: /etc/condor/config.d/99-cloud-init.conf
        owner: root
        group: root
        mode: "0644"
      notify: Reload HTCondor
  tasks:
    - name: Copy Telegraf credentials
      ansible.builtin.template:
        src: output.conf.j2
        dest: /etc/telegraf/telegraf.d/output.conf
        mode: "0640"
        owner: telegraf
        group: telegraf
      no_log: true
      notify: Restart Telegraf

  roles:
    - grycap.htcondor
    - usegalaxy-eu.autofs
