---
- name: Disable loading of DirtyClone-related modules
  ansible.builtin.copy:
    dest: /etc/modprobe.d/dirtyclone.conf
    owner: root
    group: root
    mode: "0644"
    content: |
       install esp4 /bin/false
       install esp6 /bin/false
       install rxrpc /bin/false
       blacklist esp4
       blacklist esp6
       blacklist rxrpc

- name: Unload DirtyClone-related modules if currently loaded
  ansible.builtin.command: "modprobe -r {{ item }}"
  loop:
    - esp4
    - esp6
    - rxrpc
  register: dirtyclone_rmmod
  changed_when: dirtyclone_rmmod.rc == 0
  failed_when: false

- name: Flush filesystem buffers to disk
  ansible.builtin.command: sync
  changed_when: false

- name: Drop filesystem caches
  ansible.posix.sysctl:
    name: vm.drop_caches
    value: "3"
    state: present
    sysctl_set: true
