---
htcondor_server: "build.galaxyproject.eu"
htcondor_domain: bi.uni-freiburg.de
htcondor_server_port: 9628
htcondor_shared_port: 9628
htcondor_version: "23.0"
htcondor_channel: "23.0"
htcondor_firewall_condor: false
htcondor_firewall_nfs: false
htcondor_role_execute: true
htcondor_role_manager: false
htcondor_role_submit: false

# Settings specific to the `condor_config.local.j2` configuration file.
htcondor_allow_write: "10.5.68.0/24, 132.230.223.0/24,132.230.153.0/28"
htcondor_allow_negotiator: "132.230.223.239,$(CONDOR_HOST),$(ALLOW_WRITE)"
htcondor_allow_administrator: "$(ALLOW_NEGOTIATOR)"
htcondor_system_periodic_hold: "{{ 30 * 24 * 60 * 60 }}"
htcondor_system_periodic_remove: "{{ 2 * 24 * 60 * 60 }}"
# htcondor_network_interface -> Defined per-host in host_vars.
htcondor_master_update_interval: 150
htcondor_classad_lifetime: 300
htcondor_negotiator_interval: 15
htcondor_negotiator_update_interval: 100
htcondor_schedd_interval: 60
htcondor_job_start_count: 250
htcondor_job_start_delay: 0
htcondor_claim_worklife: 120
htcondor_negotiator_post_job_rank: "isUndefined(RemoteOwner) * (10000 - TotalLoadAvg)"
